version: "3.9"

services:
  service_b:
    image: ms_service_b:latest
    networks:
      - app_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  service_a:
    image: ms_service_a:latest
    environment:
      - SERVICE_B_URL=http://service_b:5001
    networks:
      - app_net
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  nginx:
    image: ms_nginx:latest
    ports:
      - "80:80"
    networks:
      - app_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  app_net:
    driver: overlay
